### ISSUE TITLE
Create New Quicklinks

### ISSUE THREAD

**Issue by bgarner** [fgldevteam/portal#137]
LAYOUT REFERENCE FILE: 
![admin-dashboard-form-create-quicklinks](https://cloud.githubusercontent.com/assets/69516/13333568/df8a21ec-dbc4-11e5-83e3-b47b82152460.png)
- [x] required field **Name** needs asterisk
- [x] remove dashed hr tags between fields
* Quicklink Type
  - [x] Rename required field **Quicklink type** and add asterisk (consistency)
  - [x] Rename **file** to **document**
  - [x] should default to document
  - [x] reorder as: document, folder, external
  * fields/Selectors should be adjacent to their respective radio buttons
    - [x] if a field’s respective radio button is active, its action button (see below) is disabled
    - [x] selecting a radio button should not trigger a selection modal
    * types folder and file
      - [x] readonly field displaying selected folder name/path or the file name
      - [x] adjacent Select… button which triggers the folder/file select modal
    * type external
      - [x] editable field which validates for URL
      - [x] adjacent **Test** button which opens entered URL in a new tab when clicked
      - [x] **Test** is disabled when the URL is badly formed or the field is empty
  * Folder selection modal
![admin-dashboard-form-create-quicklinks-folder-select](https://cloud.githubusercontent.com/assets/69516/13332896/5b99c30e-dbc1-11e5-9ce5-2c03ee5f18bb.png)
    - [x] The icon next to an expanded folder should always be the open folder icon.
    - [x] Clicking on the folder icon should expand/collapse that folder.
    - [x] Clicking on a selected folder checkbox or name should de-select it and vice versa.
    - [x] When a folder is selected, the full path of the selected folder should be indicated within a readonly *Selected:* field at the bottom left of the modal.
    - [x] When no folder is selected, the Selected: field should be empty.
    - [x] Rename button **Select Folder** as **Select folder** (consistency)
    - [x] button **Select folder** should be disabled unless a folder is selected.
    - [x] Rename **Close** button as **Cancel** and add cancel icon.
    - [x] Successfully selecting a folder should close the modal.
  * Document selection modal
![admin-dashboard-form-create-quicklinks-document-select](https://cloud.githubusercontent.com/assets/69516/13333577/ed807008-dbc4-11e5-9974-511d27aef7cb.png)
    - [x] the icon next to any expanded folder should always be the open folder icon
    * Folder selection and the files within and given folder need to be displayed/interacted with separately (see layout reference).
      - [x] When users select a folder on the left, files within that folder are displayed on the right.
      - [x] Clicking on a selected file checkbox or name should de-select it and vice versa.
      - [x] Clicking on a folder icon should select that folder and toggle it expansion state.
      - [x] Clicking on a folder name should only select it (i.e. list its files on the right)
      - [x] When a file is selected, the file name and its folder path should be displayed within a readonly Selected: field at the bottom left of the modal (see layout reference).
      - [x] When no file is selected, the Selected: field should be empty
- [x] Remove field **Quicklink URL**
* Controls
  - [x] Move Create/Cancel buttons to bottom right of section (consistency)
  - [x] Button Create New Quicklink should be disabled until all required fields have a valid selections
  - [x] Upon success, the modal should read as follows:<br />*Quicklink_type Quicklink created* (where Quicklink_type is Document, Folder, or External)<br/>*Quicklink_detail* (where Quicklink_detail is the document title, folder name, or external URL)
  * Buttons should be:
    - [x] **Back to Dashboard** with left-arrow (back) icon
    - [x] **Create another Quicklink** with + icon
- [x] Created Quicklinks should always be added to the bottom of the current quicklink listing

**Comment by darylsuttie** [comment]
@bgarner Do you want me to break this up? (Might be tricky since a lot of the changes are inter-related.)

**Comment by darylsuttie** [comment]
Unable to test until #337 is resolved.

**Comment by darylsuttie** [comment]
Closing, mostly delivered. A few new bugs created.
