### ISSUE TITLE
Dashboard Sections: Title and Branding

### ISSUE THREAD

**Issue by bgarner** [fgldevteam/portal#140]
- [x] Merge these two sections into the Branding section, with 3 fields:
  * Title
  * Subtitle
  * Background

**Comment by bgarner** [comment]
**QA**
- [ ] Merge these two sections into the Branding section, with 3 fields:
  * Title
  * Subtitle
  * Background

**Comment by bgarner** [comment]
should be fixed in 295d362

**Comment by darylsuttie** [comment]
@bgarner 
Closing this issue.
