### ISSUE TITLE
Front-End - Featured Content - Packages

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#149]
Reference Image (label 2): 
![user-feature-landing](https://cloud.githubusercontent.com/assets/830373/13556582/68a511ee-e39a-11e5-8ae2-8953c75842bf.png)

- [x] Rename section header *Packages* to *Additional Dcouments*
* Section should behave like file/folde browsing in the Document Library:
  - [x] _Package_ links should use a prepended closed folder icon (fa-folder)
  * When a folder icon is clicked:
    - [x] the folder should expand (i.e. subfolders should be revealed underneath)
    - [x] the folder icon should change to expanded (fa-folder-open)
  * When a folder name is clicked:
    - [x] the folder's name should be displayed on the right side of the section
    - [x] the folder name should be prepended by an open folder outline icon (fa-folder-open-o)
    - [x] the files within the folder should be listed.
      * two columns only
        - [x] Title
        - [x] Added (date/time the document was added *to the library* )
      - [x] both the icon and the file/link text should trigger document view/download (depending on file type)

**Comment by bgarner** [comment]
Done in fc69805f18e5648bcff14216c7d97fc736df714f

**QA**
- [ ] Rename section header *Packages* to *Additional Dcouments*
* Section should behave like file/folde browsing in the Document Library:
  - [ ] _Package_ links should use a prepended closed folder icon (fa-folder)
  * When a folder icon is clicked:
    - [ ] the folder should expand (i.e. subfolders should be revealed underneath)
    - [ ] the folder icon should change to expanded (fa-folder-open)
  * When a folder name is clicked:
    - [ ] the folder's name should be displayed on the right side of the section
    - [ ] the folder name should be prepended by an open folder outline icon (fa-folder-open-o)
    - [ ] the files within the folder should be listed.
      * two columns only
        - [ ] Title
        - [ ] Added (date/time the document was added *to the library* )
      - [ ] both the icon and the file/link text should trigger document view/download (depending on file type)

**Comment by darylsuttie** [comment]
Since we've moved expected folder interactions to a new ticket, #223 , I'll only call out what needs to be fixed immediately.

- [ ] Only the *selected* folder and its contents should be visible on the right-hand side
![bug-fe-features-additional-docs](https://cloud.githubusercontent.com/assets/830373/13816215/1d525f6a-eb53-11e5-9c54-dae819004ffe.png)

- [ ] Top-Level folders should not be "uncollapsible". Should be able to click to toggle like any other folder. (Collapsing sibling packages when a package is expanded is still ok.)

- [ ] If a selected folder is empty (no documents), it should still have a line underneath its header in the folder listing area
![bug-fe-features-additional-docs-header-border](https://cloud.githubusercontent.com/assets/830373/13816363/b0c57e44-eb53-11e5-9fbc-288019ac9e07.png)

- [ ] If a selected folder is empty, no table headers should be displayed in the file listing area
![bug-fe-features-additional-docs-listing-no-files-no-table-headers](https://cloud.githubusercontent.com/assets/830373/13816530/53095108-eb54-11e5-8cef-eeecc1f3fabe.png)

**Comment by darylsuttie** [comment]
Shouldn't be closed. Last round of feedback not addressed as far as I know.
