### ISSUE TITLE
Front-End - Featured Content - Latest Updates

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#150]
Reference Image (label 3): 
![user-feature-landing](https://cloud.githubusercontent.com/assets/830373/13556582/68a511ee-e39a-11e5-8ae2-8953c75842bf.png)

- [x] Remove date/time stamp
- [x] Remove update details (e.g. was added in...)
- [x] Tighten up whitespace within rows (global impact ok)
- [x] Ensure document icon is clickable
- [x] Set max-height of container to ~500px with overflow set to auto

**Comment by bgarner** [comment]
time stamp and scrolling fixed in e74a960

**Comment by bgarner** [comment]
**QA**
- [ ] Remove date/time stamp
- [ ] Remove update details (e.g. was added in...)
- [ ] Tighten up whitespace within rows (global impact ok)
- [ ] Ensure document icon is clickable
- [ ] Set max-height of container to ~500px with overflow set to auto

**Comment by darylsuttie** [comment]
All good except we need to change the CSS on the containing div to just *overflow: auto;* instead of *overflow-y: scroll;*
