### ISSUE TITLE
Admin - Documents - Document Manager - Work Area - File Listing

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#156]
- [x] remove non-functional buttons **Add Sub folder** and **Edit this Folder**
* the header should:
  - [ ] display the selected folder name (see #155)
  - [ ] have the fa-folder-open-o icon prepended
- [ ] only files within the selected folder should be listed, not subfolders
- [x] remove column **Description**
- [x] insert new first column, no header, that only contains an alarm icon if a particular document is flagged as an alert
- [x] rename **Uploaded At** column to just **Uploaded**
- [x] Set the **Action** column to a fixed width wide enough to prevent the action buttons from wrapping
- [x] if a Start/End date isn't set, just leave the field blank (global impact ok)
- [x] use the day-date-time format for **Upload**, **Start**, and **End** fields
- [x] document Titles (and their icons) should appear as links and be clickable to either trigger the view modal or a download

**Comment by jyoti5337** [comment]
Already implemented
* the header should:
  - [ ] display the selected folder name (see #155)
  - [ ] have the fa-folder-open-o icon prepended
- [ ] only files within the selected folder should be listed, not subfolders

**Comment by darylsuttie** [comment]
@bgarner @jyoti5337 I thought you *weren't* going to check the tasks off, instead adding the Ready for Review Label and then once you push the changes to the server, I'd review and check things off/add comments...

**Comment by darylsuttie** [comment]
@bgarner @jyoti5337 Feedback below

This issue is now closed. Nice!

One suggestion, though: Can we insert a break between the date and time?
e.g.
Fri, Feb 26, 2016
05:47 pm
Will look cleaner.
