### ISSUE TITLE
Front-End - Core Layout - Top Toolbar

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#167]
- [x] Revise top toolbar elements order, from left-to-right:
  1. Store Number/Name (left-aligned)
  2. Log out (left-aligned)
    - [x] Rename **Log out** to **Change store** and change icon to site map
  3. Search (right-aligned)
    - [x] reduce the width by about half
    - [x] Add a **Search** button on the right side of the input field, even though the user just needs to hit Enter

**Comment by darylsuttie** [comment]
Is embedding document.write() within your HTML a best practice (as it's being used for the store name...)

**Comment by bgarner** [comment]
The `document.write` is only being used to get the storename from the local storage (ie cookie). Technically, if one wanted to and knew how to use a console, they could change their store name as it's displayed in the top bar, but on logout/login, it would change back. It's not being used for any data access, it's just a decoration.
