### ISSUE TITLE
Front-End - Core Layout - Footer

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#168]
- [x] make the year in the copyright dynamic
- [x] hide the *Report a Bug* link/functionality until it can be fleshed out

**Comment by bgarner** [comment]
fixed in 1b4fe9cb7c2d997fe2e36eaac6a3a044a48134c7

**Comment by bgarner** [comment]
bug reporting done in 4318b15d0035c9c3fd815be79351ee5aa935a752

**Comment by darylsuttie** [comment]
Looks good.
