### ISSUE TITLE
Front-End - Global Search

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#169]
*General*
- [x] Since Search persists across pages, search results should always be global
- [x] string entered into Search field should be split by spaces

*Matching*
* Match against 1 or more parts (split using spaces, punctuation, etc.) of the search string entered:
  - [x] document titles
  - [x] folder name(s)
  - [x] Communication Title, body contents
- [x] include all documents, including archived (expired) ones

*Display*
- [x] Go to the Search results page
- [ ] Re-populate the search string in the search field
- [x] Header: *Search Results*
- [x] Message (some results): *Your search returned x results.*
- [ ] string matches within results should be highlighted (bold) in some way when displayed

* Documents section
  - [x] section header: *x Matching Documents*
  - [x] Listed document titles w/ icons are links/clickable and trigger the standard modal/download
    - [ ] immediately underneath each document title, display a link to the full path of the document (e.g. Sport Chek / Flyers / FY17 / )
    - [x] clicking on a folder link takes you straight to the Library, where the appropriate folder is pre-selected

* Folders section
  - [x] section header: *x Matching Folders*
  - [x] List full path for each folder match
  - [ ] folders should be sorted alphabetically
  - [x] clicking on a folder link takes you straight to the Library, where the appropriate folder is pre-selected

* Communications section
  - [x] section header: *x Matching Communications*
  - [x] List the communications by Title
  - [ ] Communications should be sorted alphabetically
  - [x] clicking on a communication link takes you to that Communication

**Comment by darylsuttie** [comment]
@bgarner Take a look at this as a minimum viable product.

**Comment by bgarner** [comment]
90% of this is covered in 511ba6e6f8a4b7c631724d6f2b0333bbebcff28b

**Comment by darylsuttie** [comment]
Looking good over all!

- [ ] reduce the scope of the search logic for Documents to only look at document Title
- [ ] remove the *Description* column for Documents
- [ ] show & link the containing folder/path underneath each document listed, or we could make this a new issue - let me know

**Comment by darylsuttie** [comment]
- [ ] Under Folders, Paths should use / between node labels (for consistency)
- [ ] Some listed folders do match as strings but don't make sense. e.g. FY17 shows up as a top-level folder in the results list (Search 'Week 1'), but there is no such top-level folder
