### ISSUE TITLE
Admin - Featured Content - Feature Manager

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#179]
Related issue: #177 
- [x] Features should not automatically be pulled into the Active Features managed via the Dashboard
- [ ] remove the link/edit funtionality from the Feature Title
- [ ] add an Edit button in the action column in front of the delete button
- [x] remove the id column
- [ ] constrain the Cover image as much as the Thumb image
- [x] after the Title column, add a Label column

**Comment by jyoti5337** [comment]
QA
- [ ] remove the id column
- [ ] after the Title column, add a Label column

**Comment by darylsuttie** [comment]
Pending review, moving to backlog.
