### ISSUE TITLE
Admin - Featured Content - Manage Packages

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#180]
- [x] remove id column
- [ ] unlink Package Titles
- [x] add Label column
- [x] add column header _Actions_ to the actions column
- [ ] add **Edit** button in the Actions column

**Comment by jyoti5337** [comment]
QA
- [ ] remove id column
- [ ] add Label column
- [ ] add column header *Actions* to the actions column

**Comment by darylsuttie** [comment]
Moving this to backlog, pending further discussion.
