### ISSUE TITLE
Front-End - Alerts

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#184]
- [x] remove *(x active alert)* from header altogether
- [x] remove column *Description*
- [x] rename column *Alert File* to *Title*
- [x] rename column *Alert Type* to *Type*
- [x] re-order columns
  1. Type
  2. Title
  3. Date

**Comment by bgarner** [comment]
fixes for #184 specific issues in f7b98b70ef489d02653a57d29771c548765dd9fd

**Comment by darylsuttie** [comment]
- [ ] Values and Dates in the listing should not be bold
- [ ] The document titles should look like links elsewhere (e.g. blue)

**Comment by darylsuttie** [comment]
Somehow missed that the last bit of feedback wasn't addressed. I've revised the comment above, leaving two items.

**Comment by bgarner** [comment]
fixed in 904bcc3195a38f3031826a66552ec35f0ea36eab
