### ISSUE TITLE
Front-End - Alerts - Archive mode

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#185]
Pre-requisite: #184 

- [x] add an *Archive mode* toggle on the right-hand side of the Alerts header
  - [x] toggle should be off by default
  - [x] mode persists as long as the user stays within Alerts (i.e. filtering alerts by category doesn't change it)
- [x] display archived document rows differently

**Comment by darylsuttie** [comment]
- [ ] reposition archive toggle in line with *Alerts* header copy
- [ ] put toggle label inline
- [ ] rename label *Archive mode*
![adjust-archive-mode toggle-position-label-alerts](https://cloud.githubusercontent.com/assets/830373/13791352/46e155bc-eab2-11e5-9443-b109c08682dc.png)

**Comment by bgarner** [comment]
> - [ ] category filter counts should update accordingly when switching to/from archive mode (including category All)

Are we sure we want to update these counts? Don't we want these numbers to reflect the number of **active** alerts?

**Comment by darylsuttie** [comment]
Yes, as discussed, we're sure the counts should reflect what's actually listed.

**Comment by bgarner** [comment]
**QA**
- [ ] reposition archive toggle in line with *Alerts* header copy
- [ ] put toggle label inline
- [ ] rename label *Archive mode*
![adjust-archive-mode toggle-position-label-alerts](https://cloud.githubusercontent.com/assets/830373/13791352/46e155bc-eab2-11e5-9443-b109c08682dc.png)


- [ ] category filter counts should update accordingly when switching to/from archive mode (including category All)
- [ ] clicking on a category filter shouldn't disable archive mode (includes category All)
