### ISSUE TITLE
Front-End - Communications - Archive mode

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#190]
Pre-req: TBD
- [x] add an *Archive mode* toggle on the right-hand side of the *Communications* header
  - [x] toggle should be off by default
  - [x] mode persists as long as the user stays within Communications (i.e. navigating to a specific communication)
- [x] insert a new first column without a header within the file listing area
  - [x] display an archive indicator (fa-archive) in this column for any communications that are older than their end date/time

**Comment by bgarner** [comment]
> - [x] insert a new first column without a header within the file listing area
>   - [x] display an archive indicator (fa-archive) in this column for any communications that are older than their end date/time

This is done with our "blue highlighting" now

**Comment by bgarner** [comment]
**QA**

- [ ] add an *Archive mode* toggle on the right-hand side of the *Communications* header
  - [ ] toggle should be off by default
  - [ ] mode persists as long as the user stays within Communications (i.e. navigating to a specific communication)
