### ISSUE TITLE
Admin - Communications - Manage Communications - Landing

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#197]
*Communications*
- [x] replace section header copy *Communications List* with *All Communications* and style it like other sections
- [x] replaced button label *Create New Communication* with *New communication*
- [x] remove *Sender* column
- [x] add label *Action* to Action column

*These are for consistency's sake; if anything the Subject link (if it stays) should link to a read-only version of the message.*
- [x] unlink Subject for listed communications
- [x] add *Edit* button within Action column for listed communications

**Comment by darylsuttie** [comment]
Removed the parts about removing communication types.

**Comment by bgarner** [comment]
Not sure why that closed....

**Comment by darylsuttie** [comment]
Looks good.
[ ] if you have time, rename column *Send At* to *Start*

Close this whether you do the above or not.

**Comment by bgarner** [comment]
This is done, you won't see it on QA because I can't update it from home.
