### ISSUE TITLE
Front-end - Dashboard - Featured Content - Long tile labels should display nicely

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#205]
- [x] modify the tile label element so it's always bottom aligned relative to the tile, regardless of its height

![fe-dashboard-feature_tile_fix](https://cloud.githubusercontent.com/assets/830373/13716243/1f8d745a-e797-11e5-84e4-830a81ec5c07.png)

**Comment by bgarner** [comment]
**QA**
- [ ] modify the tile label element so it's always bottom aligned relative to the tile, regardless of its height
