### ISSUE TITLE
Admin - Library - Add Files - System must handle file names containing % sign

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#211]
Need this fixed and pushed ASAP.

- [x] file names containing % must not result in an unviewable file
- [x] for the upload/review process, the percentages must stick/pre-populate the title field
- [x] saving on the backend should replace the % with a safe character/string or just remove it altogether (e.g. replace with *percent*)

**Comment by bgarner** [comment]
Fixed with e884c79434779d5f9c7d7f1a87ffb26c1ea8dca1

**Comment by bgarner** [comment]
**QA**
- [ ] file names containing % must not result in an unviewable file
- [ ] for the upload/review process, the percentages must stick/pre-populate the title field
- [ ] saving on the backend should replace the % with a safe character/string or just remove it altogether (e.g. replace with *percent*)
