### ISSUE TITLE
Admin - Dashboard - Quicklinks - Deleting whatever a quicklink is pointing at breaks the site

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#213]
- [x] deleting a document assigned as a Quicklink should not break the site
- [x] deleting a folder assigned as a Quicklink should not break the site
- [x] both cases above, the associated Quicklink should be removed

**Comment by jyoti5337** [comment]
QA
- [ ] deleting a document assigned as a Quicklink should not break the site
- [ ] deleting a folder assigned as a Quicklink should not break the site
- [ ] both cases above, the associated Quicklink should be removed
