### ISSUE TITLE
Front-End - Core Layout - Left nav shouldn't scroll with page

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#214]
- [ ] Ensure left nav is fixed so banner and clickable nav elements are always visible
- [ ] Right-side content should auto-scroll

**Comment by bgarner** [comment]
fixed in c6310a51228e517df14eab8f26fc2a6fc9cd94a3

**Comment by darylsuttie** [comment]
Is this pushed to my instance? I only see a fixed footer element...

**Comment by bgarner** [comment]
@darylsuttie  - Have another look at this
