### ISSUE TITLE
Global - Library - Folders - Folder tree should be properly expanded when landing on folder page

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#230]
- [x] folder tree (left-side) should be expanded enough to reflect which folder's contents are visible visible in the Listing (right-side)
  ![improvement--global--folder-display](https://cloud.githubusercontent.com/assets/830373/13785733/4b045fee-ea9a-11e5-8279-8f410ddcf517.png)

**Comment by bgarner** [comment]
**QA**
- [ ] folder tree (left-side) should be expanded enough to reflect which folder's contents are visible visible in the Listing (right-side)
![improvement--global--folder-display](https://cloud.githubusercontent.com/assets/830373/13785733/4b045fee-ea9a-11e5-8279-8f410ddcf517.png)

**Comment by darylsuttie** [comment]
This doesn't appear to be working in Admin or the Front End. While the folder tree is expanded, the URL reverts to the top-level folder id and the file listing shown is for the top-level folder.

**Comment by darylsuttie** [comment]
I think this is working. will validate on QA once it's refreshed.

**Comment by darylsuttie** [comment]
On the westbrook instance, still seeing expanded folder tree, but the file listing is still for the root folder.
