### ISSUE TITLE
Front-End - Alerts - Active Alert count should display in Left nav

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#237]
**If there are any active alerts (i.e. within the date/time range and for the active/selected store):**
- [x] the count of those alerts should be displayed within the Alerts tab in the left nav (like for Communications)
- [x] the tab itself should have a different background colour (dark red?)

**Comment by bgarner** [comment]
this has been pushed, I didn't change the colour of the nav yet

**Comment by bgarner** [comment]
>  the tab itself should have a different background colour (dark red?)

I only changed the colour of the count notification. It looked weird with the urgent notice bright red and the regular nav style, too many different reds happening. 

My understanding is that alerts are only semi-urgent when compared to urgent notices.

**Comment by darylsuttie** [comment]
We can leave it as is for now, pending feedback from Cam, who I know is nervous about Alerts visibility. For the record, Urgent Notices are extremely rare, so any "weirdness" when there are active alerts and urgent notices would be fine.

Closing this issue.
