### ISSUE TITLE
Front-end - Communications - single communication

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#250]
- [x] remove visibility of Packages altogether
- [x] rename attachment label *x Attachments*
- [x] Just list attached documents (no tiles)
- [ ] category filters shouldn't be visible at all when viewing a specific communication
- [ ] make the left-column narrower
- [ ] in the left column, simply add a back link (use pre-pended icon fa-arrow-circle-o-left) that goes back to the communications landing

**Comment by jyoti5337** [comment]
- [ ] category filters shouldn't be visible at all when viewing a specific communication
- [ ] make the left-column narrower
- [ ] in the left column, simply add a back link (use pre-pended icon fa-arrow-circle-o-left) that goes back to the communications landing
