### ISSUE TITLE
Front-end - Communications - Landing

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#251]
- [x] *All messages* category should have a count next to it (like Alerts does)
- [x] remove *(x unread)* from the header
- [x] Active communications count (left nav) shouldn't change based on "read" state.
- [x] clickable subject line should be link blue

**Comment by jyoti5337** [comment]
QA

- [ ] *All messages* category should have a count next to it (like Alerts does)
- [ ] remove *(x unread)* from the header
- [ ] Active communications count (left nav) shouldn't change based on "read" state.
- [ ] clickable subject line should be link blue
