### ISSUE TITLE
Admin - Events - Create Event - Delay when saving an event with a lot of stores

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#302]
- [x] Event creation takes an usually long time (5+ seconds)
- [x] If the delay is unavoidable, then as soon as the user clicks _Create New Event_, an overlay should be created and some sort of progress/please wait indicator displayed until the success/fail modal appears

**Comment by darylsuttie** [comment]
Related to #329

**Comment by bgarner** [comment]
fixed in 50dd5f88ff0ea1152567a51696a8e389c9271657

**Comment by darylsuttie** [comment]
I'm not seeing the change...

**Comment by darylsuttie** [comment]
Not seeing the same Save/indicator change implemented for documents.

**Comment by darylsuttie** [comment]
Moved to Calgary release.

**Comment by darylsuttie** [comment]
Looking for the same update implemented for saving Documents. (Just checked on QA.)
