### ISSUE TITLE
Admin - Events - Create Event - Form fields don't fully reset after Creating first event

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#303]
*To replicate*
1. Successfully create a event.
2. Create another event without navigating elsewhere.

*Actual Results*
* Description field value persists
* Popup Date selectors still have dates selected even though they're not displayed in the text fields
* Store selector is completely cleared

*Expected results*
- [x] Description field should be cleared
- [x] Start/End Date selector(s) should be completely cleared 
- [x] Store selector should be reset to default All stores

**Comment by jyoti5337** [comment]
QA
- [ ] Description field should be cleared
- [ ] Start/End Date selector(s) should be completely cleared 
- [ ] Store selector should be reset to default All stores
