### ISSUE TITLE
Admin - Documents - Document Manager - Edit Document - Header

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#308]
![admin-edit-document-header](https://cloud.githubusercontent.com/assets/830373/14084998/a834f2ce-f4da-11e5-8341-033b2461eb3d.png)
- [x] Header should read: *Edit Document*
- [x] Breadcrumbs should reflect both the function (Edit) and the document Title (prior to edit)

**Comment by jyoti5337** [comment]
QA
![admin-edit-document-header](https://cloud.githubusercontent.com/assets/830373/14084998/a834f2ce-f4da-11e5-8341-033b2461eb3d.png)
- [ ] Header should read: *Edit Document*
- [ ] Breadcrumbs should reflect both the function (Edit) and the document Title (prior to edit)
