### ISSUE TITLE
Admin - Documents - Edit Document - Form Order/Labelling Adjustments

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#309]
- [x] Rename section *Edit Document* to *Document details* (see #308 )
- [x] add asterisk to *Title* field label
- [x] remove *Description* field
- [x] add asterisk to *Start* within *Start & End* field label
- [x] add asterisk to *Alert Type* field label

![admin-edit-document-form-fields](https://cloud.githubusercontent.com/assets/830373/14085325/79246fd0-f4dc-11e5-85a6-91bd8e0534e2.png)

- [x] merge *Mark document as Alert* section elements into *Document details* section as follows:
  - [x] Store selector should immediately follow *Start & End*
  - [x] *This document is an alert* Alert checkbox and Alert Type selector should follow

**Comment by jyoti5337** [comment]
QA
- [ ] Rename section *Edit Document* to *Document details* (see #308 )
- [ ] add asterisk to *Title* field label
- [ ] remove *Description* field
- [ ] add asterisk to *Start* within *Start & End* field label
- [ ] add asterisk to *Alert Type* field label
- [ ] merge *Mark document as Alert* section elements into *Document details* section as follows:
  - [ ] Store selector should immediately follow *Start & End*
  - [ ] *This document is an alert* Alert checkbox and Alert Type selector should follow
