### ISSUE TITLE
Admin - Documents - Edit - Extreme delay before confirmation when Saving changes

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#329]
When a change is saved, there's a 5+ second delay where nothing happens.

[ ] ensure that as soon as a valid *Save changes* click happens, an overlay covers the screen a load gif appears (i.e. have the success modal appear with a load gif inside and refresh its contents once the commit is completed)

**Comment by darylsuttie** [comment]
Note: The delay seems to correlate directly with the number of stores targeted. (This doesn't alter the request)

**Comment by bgarner** [comment]
fixed in 50dd5f88ff0ea1152567a51696a8e389c9271657

**Comment by darylsuttie** [comment]
The implemented solution (status within the button) works, but creates a new problem:
After the save is completed, the button says saved with a checkmark, but since the user can still make more edits:
[ ] after a successful save, the save button should revert to *save changes* with the save icon if any of the form fields are put into focus...

**Comment by bgarner** [comment]
I have it revert to it's original state after 2 seconds. I have done the same thing for the event creation.

**Comment by darylsuttie** [comment]
Works for me.
