### ISSUE TITLE
Admin - Package Listing - Backend Package name displayed instead of title

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#345]
- [ ] ensure the package title is displayed in the title column
![packagetitle](https://cloud.githubusercontent.com/assets/830373/14397479/c9e5d8c0-fd9a-11e5-8912-8d4ffbe4f89e.png)

**Comment by jyoti5337** [comment]
This is an issue with old content

**Comment by darylsuttie** [comment]
just realised that. closing.
