### ISSUE TITLE
Hitting Cancel while editing a document takes you to Urgent Notices management

### ISSUE THREAD

**Issue by darylsuttie** [fgldevteam/portal#371]
**To replicate**
* Via the Library, edit a document
* Click *Cancel*

**Expected result**
* user is returned to the Library landing
* expanded folder should be the same as the one from which they had selected a document for editing

**Actual result**
* user is taken to urgent notices management

**Comment by darylsuttie** [comment]
Related: #336

**Comment by jyoti5337** [comment]
Not an issue
