### ISSUE TITLE
Saving an Event Clears its Information

### ISSUE THREAD

**Issue by robpetrollini** [fgldevteam/portal#378]
After a New Event is created and saved, all the information in the WYSIWYG disappears:
![image](https://cloud.githubusercontent.com/assets/18467414/15441836/69da1704-1e9a-11e6-86a8-05814fa560d9.png)

**Comment by robpetrollini** [comment]
I believe this was developed so the user could quickly input multiple Events. However, the list of stores is not clearing.

**Comment by jyoti5337** [comment]
addressed in 724ae75ccc068e492e4a1e3b130bb8bfeca8fd9b
