### ISSUE TITLE
Show Archive Toggle Occasionally Showing Error Message

### ISSUE THREAD

**Issue by robpetrollini** [fgldevteam/portal#379]
The Show Archive toggle is from Off to On is on occasion is showing the following error:

![image](https://cloud.githubusercontent.com/assets/18467414/15442620/9f7d0a24-1e9f-11e6-983c-2fb3c3dbef54.png)

**Comment by jyoti5337** [comment]
addressed in 80d9d7dc1161bfa5bb2b915a40c984200b859ed7
