### ISSUE TITLE
Create an Event - Target Stores Not Selected

### ISSUE THREAD

**Issue by robpetrollini** [fgldevteam/portal#382]
After entering a list of store numbers and clicking _Create New Event,_ an error message occurs:
 
![image](https://cloud.githubusercontent.com/assets/18467414/15512888/596f0278-219f-11e6-97d8-11151d5cdc21.png)

![image](https://cloud.githubusercontent.com/assets/18467414/15512941/a1e2d304-219f-11e6-84ae-6a658c5bf161.png)

**Comment by robpetrollini** [comment]
It appears the error message / failure to publish occurs when the list of stores is long. 
When I update the calendar for five stores, it works.

**Comment by robpetrollini** [comment]
The error has now occurred with one store selected.

**Comment by robpetrollini** [comment]
The error is occurring with a variety of numbers. I will stop inputting store numbers until this is fixed.

**Comment by jyoti5337** [comment]
addressed in 724ae75ccc068e492e4a1e3b130bb8bfeca8fd9b
