### ISSUE TITLE
Calendar Week View and Day View Not Displaying Information

### ISSUE THREAD

**Issue by robpetrollini** [fgldevteam/portal#383]
The _month_ calendar view is displaying information, however, the _week_ and _day_ view is not displaying content.

![image](https://cloud.githubusercontent.com/assets/18467414/15518228/14f617ca-21b9-11e6-846f-bf9629679fd2.png)

![image](https://cloud.githubusercontent.com/assets/18467414/15518238/1ff80688-21b9-11e6-8043-59335f88ebe7.png)

![image](https://cloud.githubusercontent.com/assets/18467414/15518257/3659175a-21b9-11e6-9be7-4d882f8e632b.png)

**Comment by jyoti5337** [comment]
similar to #385
