### ISSUE TITLE
Atmosphere Communication Types 

### ISSUE THREAD

**Issue by robpetrollini** [fgldevteam/portal#384]
There are no _Communication Types_ listed in _Manage Communication Types,_ however, they appear on the front-end. I suspect they are pulling from the Sport Chek side of the site.

![image](https://cloud.githubusercontent.com/assets/18467414/15519210/9fcf9fa2-21bd-11e6-953d-e1086a0c3ae5.png)

![image](https://cloud.githubusercontent.com/assets/18467414/15519218/a8164814-21bd-11e6-88dc-9ebba5a5506e.png)

**Comment by jyoti5337** [comment]
addressed in cef8f3c7eeefefdc9dddafa46801ba1902aba134
