### ISSUE TITLE
Multiple Items in Calendar are Not Displaying

### ISSUE THREAD

**Issue by robpetrollini** [fgldevteam/portal#385]
When _+ # more_ is displayed on the calendar, the additional items are not loading.

![image](https://cloud.githubusercontent.com/assets/18467414/15519393/7f2e236c-21be-11e6-99d4-afafe1d4992d.png)

**Comment by jyoti5337** [comment]
This is due to the event starting and ending at the same datetime. If an all day event needs to be created for today e.g., start would be 2016-05-24 and end would be 2016-05-25 (today midnight to tomorrow midnight would be one full day)
