### ISSUE TITLE
PDF Viewer Does Not Render Select Sign Files

### ISSUE THREAD

**Issue by robpetrollini** [fgldevteam/portal#388]
PDF Viewer is having challenges rendering some of the sign files. The signs print correctly once downloaded, as well as display correctly on the current Ops Portal.

Megha and I have spoken about this in person. I flagged this for Cam and he would like this fixed.
I don't believe the issue stems from how the PDF is created as it is not a complex file. Only a font with a fill and stroke.

![image](https://cloud.githubusercontent.com/assets/18467414/15584701/f82bc6fe-2338-11e6-81cd-d4c68817e017.png)

**Comment by bgarner** [comment]
PDFs need to be flattened.

**Comment by robpetrollini** [comment]
The file is printing correctly when downloaded. The issue is only happening in the PDF viewer.

**Comment by bgarner** [comment]
For it to work in the viewer, it needs to be flattened.

**Comment by robpetrollini** [comment]
These are the two settings used when signs are created. Can you advise on how to flatten? 

![image](https://cloud.githubusercontent.com/assets/18467414/15591209/e004d03c-2358-11e6-976e-29845437c490.png)


![image](https://cloud.githubusercontent.com/assets/18467414/15591221/ea233ffe-2358-11e6-9b82-d9702da85593.png)

**Comment by bgarner** [comment]
Fonts need to be converted to outlines.

**Comment by robpetrollini** [comment]
That is not a solution. The Playbook is saved as a PDF with the same settings and it is working fine. The Playbook is a more complex file than signs with images and a variety of fonts.
A PDF should embed and display the fonts correctly. I suspect this PDF viewer is not ideal.

**Comment by bgarner** [comment]
Give it a try and see how it looks

**Comment by robpetrollini** [comment]
Outlines will work, however, that will not allow the original signs to be edited as they so often are. Sign templates are also edited and re-used often, so having no editable fonts would be a set-back. Converting to Outlines is an extra step that Tara, Amanda and Cassandra do not have time for. The current Portal renders the signs fine so this new site should as well.

**Comment by bgarner** [comment]
Just save a separate non-editable version and keep your working file.

**Comment by robpetrollini** [comment]
That won't work with the volume of sign files we work with. Particularly during the holiday season. Cam has been briefed. He'll bring this up.

**Comment by bgarner** [comment]
We've changed how this works from the old portal to accommodate tablets.
