### ISSUE TITLE
Duplication Issue

### ISSUE THREAD

**Issue by robpetrollini** [fgldevteam/portal#390]
_Pasting this email thread as the issue should be fixed_ 

Should also note that I cannot delete the files attached to this communication: http://fdms1ap01.unix.ctcwest.ctc/0234/communication/show/32?

I suspect it is all connected to this issue

Sorry – even when leaving the communication, I cannot delete the duplicate files.

From: Petrollini, Rob 
Sent: May-27-16 1:40 PM
To: Jyoti, Megha
Subject: RE: Duplication Issue

I think the issue arises when saving and then continuing to edit.
Cannot delete the duplicate files below unless I leave the communication and return to it.

![image](https://cloud.githubusercontent.com/assets/18467414/15691482/3f7dcbb8-2746-11e6-8ad1-c8134d88cdf4.png)

From: Jyoti, Megha 
Sent: May-27-16 1:31 PM
To: Petrollini, Rob
Subject: Re: Duplication Issue

Can you send me the steps you followed when this issue happened? I tried it but did not find  any issue on my machine.

Thanks,
Megha

On May 27, 2016, at 1:20 PM, Petrollini, Rob <Rob.Petrollini@fglsports.com> wrote:

Can you remind me if this was addressed? https://github.com/fgldevteam/portal/issues/381
It is also happening when editing a Feature. Documents and Packages are duplicating.
 
Thanks,
Rob

**Comment by jyoti5337** [comment]
Duplicate issue #375
